/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 Docs -> https://docusaurus.io/docs/next/sidebar

 */

// @ts-nocheck

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */


const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  //tutorialSidebar: [
  //  'a-gentle-introduction',
  //
  //{
  //  type: 'category',
  //  label: 'Tutorial Extras',
  //  items: [
  //    'tutorial-extras/manage-docs-versions',
  //    'tutorial-extras/translate-your-site',
  //  ],
  //},
  //],
};

module.exports = {
  sidebar: [
    {
      type: 'doc',
      id: 'gentle-introduction',
    },
    {
      type: 'doc',
      id: 'airdrop-specs',
    }
  ],
};
